### ISSUE TITLE
Crash during brain registration

### ISSUE THREAD

**Issue by IIDamienII** [lmbneuron/D-LMBmap#3]
Hi,

I tried the software and everything worked well before I come to the brain registration. I import in the new window my segmented brain and my style tranfered brain (as shown in the video) and when I click on Action>Register, the software start the calculation and crash systematically (all the windows are closed). Is there anything I can do to solve the issue ? 

Thank you for your help,
Damien

**Comment by lmbneuron** [comment]
We have updated the software with this problem solved, please try it! If you have any further questions when using the software, please contact us.
